### PR TITLE
fixes #3607 - Style adjustments org page

### LINKED ISSUE #3607: Style adjustments org page
Org page space between title and first section is a bit too big
org
loc

### PR DESCRIPTION
**Pull request by teodorescuserban**
@danmihaila DO NOT MERGE YET! :)

### CODE REVIEW

**Comment by aalecs** [comment]
test this please

**Comment by aalecs** [comment]
test this please

**Comment by teodorescuserban** [comment]
test this please

**Comment by teodorescuserban** [comment]
test this please

**Pull request merged**
