### PR TITLE
Marianne history 2 3

### PR DESCRIPTION
**Pull request by mbellotti**
Might as well merge now. Can also wait.

### CODE REVIEW

**Comment by alexandru-m-g** [comment]
@mbellotti Please don't commit just the less files. There's no automatic compilation done for this on the server so we need the CSS as well.

**Comment by mbellotti** [comment]
Okay! I didn't realize that. I will correct tonight :)

**Comment by danmihaila** [comment]
Let me know when the new pr is ready

**Comment by mbellotti** [comment]
Didn't you just create it and merge it yourself? :)

**Comment by danmihaila** [comment]
It gave an error, i think you were pushing a second commit. I thought it is still work in progress....

**Comment by mbellotti** [comment]
Yeah the timing of it was pretty close. You surprised me, but I was going to open up the PR myself anyway. You just beat me to it by a few seconds haha :)

**Pull request merged**
