### PR TITLE
Marianne sprint63

### PR DESCRIPTION
**Pull request by mbellotti**

### CODE REVIEW

**Comment by aalecs** [comment]
@mbellotti This pull request has a fix for 64 which we can't include since we're accepting 2 fixes for sprint 63 already this late. Can you cherrypick them into another branch and pull request from there? Thanks!
PS: Try to fix your VM's date because your commits look 9 days old :)

**Comment by mbellotti** [comment]
Ugh really? I thought I fixed the date already :/ Sorry will reboot it.

On Wed, Aug 26, 2015 at 5:27 AM, Alexandru Artimon <notifications@github.com

**Comment by mbellotti** [comment]
Done

**Comment by aalecs** [comment]
I talked with Aidan and we want enough time to test #3318, so we'll include this fixes in sprint 64. No need for a separate branch, thanks

**Pull request merged**
