### PR TITLE
Marianne history 2 3

### PR DESCRIPTION
**Pull request by mbellotti**
Phew! Got it all done :)

### CODE REVIEW

**Comment by danmihaila** [comment]
@mbellotti please review Arti's comments and fix those issues and make another PR to be merged. thanks

**Comment by mbellotti** [comment]
Okay... so what does @aalecs suggest when the browser will not honor css if not !important?

**Comment by aalecs** [comment]
Not taking the easy way out and to try to override the style by increasing selector specificity :)

**Comment by mbellotti** [comment]
Oh awesome. I love it when we hold up a whole deploy over petty pedantic things.

**Pull request merged**
